//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eknowID.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMSHomePage
    {
        public int CMSHomeID { get; set; }
        public string testimonials_content { get; set; }
        public string testimonials_Sign_Name { get; set; }
        public string testimonials_Sign_CompanyName { get; set; }
        public string testimonials_imageName { get; set; }
        public string Blog_Header { get; set; }
        public string Blog_Content { get; set; }
        public string YoutubeSrc { get; set; }
        public bool PreviewFlag { get; set; }
    }
}
