//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eknowID.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public Coupon()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int CouponId { get; set; }
        public string CouponCode { get; set; }
        public int CouponDiscountTypeId { get; set; }
        public decimal DiscountValue { get; set; }
    
        public virtual CouponDiscountType CouponDiscountType { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
