//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eknowID.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourtLocation
    {
        public int CourtLocationId { get; set; }
        public string OfficeName { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> CourtTypeId { get; set; }
        public Nullable<int> StateId { get; set; }
    
        public virtual City City { get; set; }
        public virtual CourtType CourtType { get; set; }
        public virtual State State { get; set; }
    }
}
