//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eknowID.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugVerification
    {
        public DrugVerification()
        {
            this.DrugVerificationDetails = new HashSet<DrugVerificationDetail>();
        }
    
        public int DrugVerificationId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<DrugVerificationDetail> DrugVerificationDetails { get; set; }
    }
}
