//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eknowID.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EknowIDEntities : DbContext
    {
        public EknowIDEntities()
            : base("name=EknowIDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccountRef> AccountRefs { get; set; }
        public DbSet<AlacartReport> AlacartReports { get; set; }
        public DbSet<Candidate> Candidates { get; set; }
        public DbSet<CardList> CardLists { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<CMSHomePage> CMSHomePages { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<County> Counties { get; set; }
        public DbSet<Coupon> Coupons { get; set; }
        public DbSet<CouponDiscountType> CouponDiscountTypes { get; set; }
        public DbSet<CourtLocation> CourtLocations { get; set; }
        public DbSet<CourtType> CourtTypes { get; set; }
        public DbSet<District> Districts { get; set; }
        public DbSet<DrugVerification> DrugVerifications { get; set; }
        public DbSet<DrugVerificationDetail> DrugVerificationDetails { get; set; }
        public DbSet<EducationalDetail> EducationalDetails { get; set; }
        public DbSet<ELMAH_Error> ELMAH_Error { get; set; }
        public DbSet<EmailSendLog> EmailSendLogs { get; set; }
        public DbSet<EmploymentDetail> EmploymentDetails { get; set; }
        public DbSet<ForgotPassword> ForgotPasswords { get; set; }
        public DbSet<IdentificationType> IdentificationTypes { get; set; }
        public DbSet<LicenseInfo> LicenseInfoes { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<OrderOptReport> OrderOptReports { get; set; }
        public DbSet<OrderState> OrderStates { get; set; }
        public DbSet<OrderType> OrderTypes { get; set; }
        public DbSet<PaymentWalletHistory> PaymentWalletHistories { get; set; }
        public DbSet<Plan> Plans { get; set; }
        public DbSet<PlanReport> PlanReports { get; set; }
        public DbSet<PostGraduationDetail> PostGraduationDetails { get; set; }
        public DbSet<Profession> Professions { get; set; }
        public DbSet<ProfessionPlan> ProfessionPlans { get; set; }
        public DbSet<ProfessionReport> ProfessionReports { get; set; }
        public DbSet<ReferenceInfo> ReferenceInfoes { get; set; }
        public DbSet<ReferenceType> ReferenceTypes { get; set; }
        public DbSet<Report> Reports { get; set; }
        public DbSet<ReportType> ReportTypes { get; set; }
        public DbSet<SecQuestion> SecQuestions { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<TransactionLog> TransactionLogs { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserAdditionalSkill> UserAdditionalSkills { get; set; }
        public DbSet<UserEducationalDetail> UserEducationalDetails { get; set; }
        public DbSet<UserEmploymentDetail> UserEmploymentDetails { get; set; }
        public DbSet<UserLanuagesKnown> UserLanuagesKnowns { get; set; }
        public DbSet<UserLicenseInfo> UserLicenseInfoes { get; set; }
        public DbSet<UserPostGraduation> UserPostGraduations { get; set; }
        public DbSet<UserReferenceInfo> UserReferenceInfoes { get; set; }
        public DbSet<UserSkill> UserSkills { get; set; }
        public DbSet<ValidationRule> ValidationRules { get; set; }
        public DbSet<WalletBalance> WalletBalances { get; set; }
        public DbSet<Log> Logs { get; set; }
        public DbSet<OrderAdditionalCharge> OrderAdditionalCharges { get; set; }
        public DbSet<StateDistrictCourtFee> StateDistrictCourtFees { get; set; }
        public DbSet<StateCriminalCourtFee> StateCriminalCourtFees { get; set; }
        public DbSet<StateCountyCourtFee> StateCountyCourtFees { get; set; }
    }
}
