//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eknowID.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmploymentDetail
    {
        public int EmploymentDetailId { get; set; }
        public int OrderId { get; set; }
        public Nullable<int> StateId { get; set; }
        public string OrgName { get; set; }
        public string City { get; set; }
        public string Telephone { get; set; }
        public string PositionTitle { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> StartMonth { get; set; }
        public Nullable<int> StartYear { get; set; }
        public Nullable<int> EndMonth { get; set; }
        public Nullable<int> EndYear { get; set; }
        public Nullable<bool> IsAttending { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual State State { get; set; }
    }
}
