//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eknowID.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForgotPassword
    {
        public int ForgotPasswordId { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> ForgotDate { get; set; }
        public Nullable<bool> IsUsed { get; set; }
    
        public virtual User User { get; set; }
    }
}
