//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eknowID.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.AlacartReports = new HashSet<AlacartReport>();
            this.Candidates = new HashSet<Candidate>();
            this.DrugVerificationDetails = new HashSet<DrugVerificationDetail>();
            this.EducationalDetails = new HashSet<EducationalDetail>();
            this.EmploymentDetails = new HashSet<EmploymentDetail>();
            this.LicenseInfoes = new HashSet<LicenseInfo>();
            this.OrderOptReports = new HashSet<OrderOptReport>();
            this.OrderStates = new HashSet<OrderState>();
            this.ReferenceInfoes = new HashSet<ReferenceInfo>();
            this.TransactionLogs = new HashSet<TransactionLog>();
            this.OrderAdditionalCharges = new HashSet<OrderAdditionalCharge>();
        }
    
        public int OrderId { get; set; }
        public int UserId { get; set; }
        public int ProfessionId { get; set; }
        public int PlanId { get; set; }
        public string Description { get; set; }
        public string CorrelationId { get; set; }
        public string TransactionId { get; set; }
        public Nullable<int> CouponId { get; set; }
        public Nullable<System.DateTime> PurchasedDate { get; set; }
        public Nullable<decimal> DiscountAmt { get; set; }
        public Nullable<decimal> PaidAmt { get; set; }
        public Nullable<int> OrderTypeID { get; set; }
        public System.Guid AssessmentId { get; set; }
        public Nullable<bool> IsResendEmail { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ResendEmailCount { get; set; }
        public Nullable<decimal> RefundAmt { get; set; }
        public string PendingNotes { get; set; }
    
        public virtual ICollection<AlacartReport> AlacartReports { get; set; }
        public virtual ICollection<Candidate> Candidates { get; set; }
        public virtual Coupon Coupon { get; set; }
        public virtual ICollection<DrugVerificationDetail> DrugVerificationDetails { get; set; }
        public virtual ICollection<EducationalDetail> EducationalDetails { get; set; }
        public virtual ICollection<EmploymentDetail> EmploymentDetails { get; set; }
        public virtual ICollection<LicenseInfo> LicenseInfoes { get; set; }
        public virtual OrderType OrderType { get; set; }
        public virtual Plan Plan { get; set; }
        public virtual Profession Profession { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<OrderOptReport> OrderOptReports { get; set; }
        public virtual ICollection<OrderState> OrderStates { get; set; }
        public virtual ICollection<ReferenceInfo> ReferenceInfoes { get; set; }
        public virtual ICollection<TransactionLog> TransactionLogs { get; set; }
        public virtual ICollection<OrderAdditionalCharge> OrderAdditionalCharges { get; set; }
    }
}
