//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eknowID.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentWalletHistory
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<decimal> Deposite { get; set; }
        public Nullable<decimal> Withdrawal { get; set; }
        public string TransactionId { get; set; }
        public System.DateTime InsertedDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
