//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eknowID.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        public Plan()
        {
            this.Orders = new HashSet<Order>();
            this.PlanReports = new HashSet<PlanReport>();
            this.ProfessionPlans = new HashSet<ProfessionPlan>();
        }
    
        public int PlanId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> RateOff { get; set; }
        public Nullable<bool> HasProfessionRelationship { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<PlanReport> PlanReports { get; set; }
        public virtual ICollection<ProfessionPlan> ProfessionPlans { get; set; }
    }
}
