//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eknowID.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profession
    {
        public Profession()
        {
            this.Orders = new HashSet<Order>();
            this.ProfessionPlans = new HashSet<ProfessionPlan>();
            this.ProfessionReports = new HashSet<ProfessionReport>();
        }
    
        public int ProfessionId { get; set; }
        public string Name { get; set; }
        public string ShortDesc { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<ProfessionPlan> ProfessionPlans { get; set; }
        public virtual ICollection<ProfessionReport> ProfessionReports { get; set; }
    }
}
