//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eknowID.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfessionPlan
    {
        public int ProfessionPlanId { get; set; }
        public Nullable<int> ProfessionId { get; set; }
        public Nullable<int> PlanId { get; set; }
    
        public virtual Plan Plan { get; set; }
        public virtual Profession Profession { get; set; }
    }
}
