//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eknowID.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenceInfo
    {
        public int ReferenceInfoId { get; set; }
        public int OrderId { get; set; }
        public string Name { get; set; }
        public string Relationship { get; set; }
        public string MobileNumber { get; set; }
        public string YearsKnown { get; set; }
        public int ReferenceTypeId { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ReferenceType ReferenceType { get; set; }
    }
}
