//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eknowID.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public Report()
        {
            this.AlacartReports = new HashSet<AlacartReport>();
            this.OrderOptReports = new HashSet<OrderOptReport>();
            this.PlanReports = new HashSet<PlanReport>();
            this.ProfessionReports = new HashSet<ProfessionReport>();
        }
    
        public int ReportId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> ReportTypeID { get; set; }
        public bool IsEmpInfoReq { get; set; }
        public bool IsEduInfoReq { get; set; }
        public bool IsLicInfoReq { get; set; }
        public bool IsRefInfoReq { get; set; }
        public bool IsDrugVerificationReq { get; set; }
        public int CriminalCheckNumber { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string TurnaroundTime { get; set; }
        public string reportShortDesrript { get; set; }
        public bool IsMultipleCheckEnabled { get; set; }
        public int MaxVerificationCount { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<AlacartReport> AlacartReports { get; set; }
        public virtual ICollection<OrderOptReport> OrderOptReports { get; set; }
        public virtual ICollection<PlanReport> PlanReports { get; set; }
        public virtual ICollection<ProfessionReport> ProfessionReports { get; set; }
        public virtual ReportType ReportType { get; set; }
    }
}
