//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eknowID.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecQuestion
    {
        public SecQuestion()
        {
            this.Users = new HashSet<User>();
        }
    
        public int SecQuestionId { get; set; }
        public string Question { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
