//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eknowID.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.Counties = new HashSet<County>();
            this.CourtLocations = new HashSet<CourtLocation>();
            this.Districts = new HashSet<District>();
            this.EducationalDetails = new HashSet<EducationalDetail>();
            this.EmploymentDetails = new HashSet<EmploymentDetail>();
            this.LicenseInfoes = new HashSet<LicenseInfo>();
            this.PostGraduationDetails = new HashSet<PostGraduationDetail>();
            this.Users = new HashSet<User>();
            this.UserEducationalDetails = new HashSet<UserEducationalDetail>();
            this.UserEmploymentDetails = new HashSet<UserEmploymentDetail>();
            this.UserLicenseInfoes = new HashSet<UserLicenseInfo>();
            this.StateDistrictCourtFees = new HashSet<StateDistrictCourtFee>();
            this.StateCountyCourtFees = new HashSet<StateCountyCourtFee>();
        }
    
        public int StateId { get; set; }
        public string Name { get; set; }
        public string AlphaCode { get; set; }
        public Nullable<int> ValidationRuleId { get; set; }
    
        public virtual ICollection<County> Counties { get; set; }
        public virtual ICollection<CourtLocation> CourtLocations { get; set; }
        public virtual ICollection<District> Districts { get; set; }
        public virtual ICollection<EducationalDetail> EducationalDetails { get; set; }
        public virtual ICollection<EmploymentDetail> EmploymentDetails { get; set; }
        public virtual ICollection<LicenseInfo> LicenseInfoes { get; set; }
        public virtual ICollection<PostGraduationDetail> PostGraduationDetails { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<UserEducationalDetail> UserEducationalDetails { get; set; }
        public virtual ICollection<UserEmploymentDetail> UserEmploymentDetails { get; set; }
        public virtual ICollection<UserLicenseInfo> UserLicenseInfoes { get; set; }
        public virtual ValidationRule ValidationRule { get; set; }
        public virtual ICollection<StateDistrictCourtFee> StateDistrictCourtFees { get; set; }
        public virtual ICollection<StateCountyCourtFee> StateCountyCourtFees { get; set; }
    }
}
