//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eknowID.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateCriminalCourtFee
    {
        public int StateId { get; set; }
        public string Name { get; set; }
        public string AlphaCode { get; set; }
        public string Availability { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public string TurnAroundTime { get; set; }
        public bool Deleted { get; set; }
    }
}
