//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eknowID.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReferenceInfo
    {
        public int UserReferenceInfoId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> ReferenceTypeId { get; set; }
        public string Name { get; set; }
        public string Relationship { get; set; }
        public string MobileNumber { get; set; }
        public string YearsKnown { get; set; }
    
        public virtual ReferenceType ReferenceType { get; set; }
        public virtual User User { get; set; }
    }
}
