//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eknowID.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLanuagesKnown
    {
        public int UserLanuagesKnownId { get; set; }
        public Nullable<int> UserSkillId { get; set; }
        public string Lanuage { get; set; }
    
        public virtual UserSkill UserSkill { get; set; }
    }
}
