//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eknowID.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValidationRule
    {
        public ValidationRule()
        {
            this.States = new HashSet<State>();
        }
    
        public int ValidationRuleId { get; set; }
        public string Description { get; set; }
        public string RegularExpression { get; set; }
        public Nullable<bool> IsSSN { get; set; }
        public Nullable<bool> IsLastCharcter { get; set; }
    
        public virtual ICollection<State> States { get; set; }
    }
}
