////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:4.0.30319.18010
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//using System.Xml.Serialization;

//// 
//// This source code was auto-generated by xsd, Version=4.0.30319.1.
//// 


///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
//public partial class PersonName {
    
//    private string givenNameField;
    
//    private string middleNameField;
    
//    private string familyNameField;
    
//    private string formattedNameField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string GivenName {
//        get {
//            return this.givenNameField;
//        }
//        set {
//            this.givenNameField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string MiddleName {
//        get {
//            return this.middleNameField;
//        }
//        set {
//            this.middleNameField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string FamilyName {
//        get {
//            return this.familyNameField;
//        }
//        set {
//            this.familyNameField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string FormattedName {
//        get {
//            return this.formattedNameField;
//        }
//        set {
//            this.formattedNameField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
//public partial class PostalAddress {
    
//    private string postalCodeField;
    
//    private string regionField;
    
//    private string municipalityField;
    
//    private PostalAddressDeliveryAddress[] deliveryAddressField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string PostalCode {
//        get {
//            return this.postalCodeField;
//        }
//        set {
//            this.postalCodeField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string Region {
//        get {
//            return this.regionField;
//        }
//        set {
//            this.regionField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string Municipality {
//        get {
//            return this.municipalityField;
//        }
//        set {
//            this.municipalityField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("DeliveryAddress", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public PostalAddressDeliveryAddress[] DeliveryAddress {
//        get {
//            return this.deliveryAddressField;
//        }
//        set {
//            this.deliveryAddressField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//public partial class PostalAddressDeliveryAddress {
    
//    private string addressLineField;
    
//    private string streetNameField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string AddressLine {
//        get {
//            return this.addressLineField;
//        }
//        set {
//            this.addressLineField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string StreetName {
//        get {
//            return this.streetNameField;
//        }
//        set {
//            this.streetNameField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
//public partial class BackgroundCheck {
    
//    private BackgroundSearchPackage[] backgroundSearchPackageField;
    
//    private string userIdField;
    
//    private string passwordField;

//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("BackgroundSearchPackage", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public BackgroundSearchPackage[] BackgroundSearchPackage
//    {
//        get
//        {
//            return this.backgroundSearchPackageField;
//        }
//        set
//        {
//            this.backgroundSearchPackageField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string userId {
//        get {
//            return this.userIdField;
//        }
//        set {
//            this.userIdField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string password {
//        get {
//            return this.passwordField;
//        }
//        set {
//            this.passwordField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//public partial class BackgroundSearchPackage {
    
//    private string referenceIdField;
    
//    private PersonalData[] personalDataField;
    
//    private Screenings[] screeningsField;
    
//    private string actionField;
    
//    private string typeField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string ReferenceId {
//        get {
//            return this.referenceIdField;
//        }
//        set {
//            this.referenceIdField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("PersonalData", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public PersonalData[] PersonalData {
//        get {
//            return this.personalDataField;
//        }
//        set {
//            this.personalDataField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("Screenings", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public Screenings[] Screenings {
//        get {
//            return this.screeningsField;
//        }
//        set {
//            this.screeningsField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string action {
//        get {
//            return this.actionField;
//        }
//        set {
//            this.actionField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string type {
//        get {
//            return this.typeField;
//        }
//        set {
//            this.typeField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//public partial class PersonalData {
    
//    private string emailAddressField;
    
//    private string telephoneField;
    
//    private PersonName[] personNameField;
    
//    private PersonName[][] aliasesField;
    
//    private DemographicDetail[] demographicDetailField;
    
//    private PostalAddress[] postalAddressField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string EmailAddress {
//        get {
//            return this.emailAddressField;
//        }
//        set {
//            this.emailAddressField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string Telephone {
//        get {
//            return this.telephoneField;
//        }
//        set {
//            this.telephoneField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("PersonName")]
//    public PersonName[] PersonName {
//        get {
//            return this.personNameField;
//        }
//        set {
//            this.personNameField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    [System.Xml.Serialization.XmlArrayItemAttribute("PersonName", typeof(PersonName), IsNullable=false)]
//    public PersonName[][] Aliases {
//        get {
//            return this.aliasesField;
//        }
//        set {
//            this.aliasesField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("DemographicDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public DemographicDetail[] DemographicDetail {
//        get {
//            return this.demographicDetailField;
//        }
//        set {
//            this.demographicDetailField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("PostalAddress")]
//    public PostalAddress[] PostalAddress {
//        get {
//            return this.postalAddressField;
//        }
//        set {
//            this.postalAddressField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//public partial class DemographicDetail {
    
//    private string dateOfBirthField;
    
//    private BackgroundCheckBackgroundSearchPackagePersonalDataDemographicDetailGovernmentId[] governmentIdField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string DateOfBirth {
//        get {
//            return this.dateOfBirthField;
//        }
//        set {
//            this.dateOfBirthField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("GovernmentId", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
//    public BackgroundCheckBackgroundSearchPackagePersonalDataDemographicDetailGovernmentId[] GovernmentId {
//        get {
//            return this.governmentIdField;
//        }
//        set {
//            this.governmentIdField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//public partial class BackgroundCheckBackgroundSearchPackagePersonalDataDemographicDetailGovernmentId {
    
//    private string countryCodeField;
    
//    private string issuingAuthorityField;
    
//    private string valueField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string countryCode {
//        get {
//            return this.countryCodeField;
//        }
//        set {
//            this.countryCodeField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string issuingAuthority {
//        get {
//            return this.issuingAuthorityField;
//        }
//        set {
//            this.issuingAuthorityField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlTextAttribute()]
//    public string Value {
//        get {
//            return this.valueField;
//        }
//        set {
//            this.valueField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//public partial class Screenings {
    
//    public CreditScreening Screening
//    {
//        get;
//        set;
//    }
//    //private Screening[] screeningField;
    
//    //private BackgroundCheckBackgroundSearchPackageScreeningsAdditionalItems[] additionalItemsField;
    
//    ///// <remarks/>
//    //[System.Xml.Serialization.XmlElementAttribute("Screening", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    //public Screening[] Screening {
//    //    get {
//    //        return this.screeningField;
//    //    }
//    //    set {
//    //        this.screeningField = value;
//    //    }
//    //}
    
//    ///// <remarks/>
//    //[System.Xml.Serialization.XmlElementAttribute("AdditionalItems", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    //public BackgroundCheckBackgroundSearchPackageScreeningsAdditionalItems[] AdditionalItems {
//    //    get {
//    //        return this.additionalItemsField;
//    //    }
//    //    set {
//    //        this.additionalItemsField = value;
//    //    }
//    //}
//}

//public partial class CreditScreening
//{
//    public CreditVendor Vendor
//    {
//        get;
//        set;
//    }
//}

//public partial class CreditVendor
//{
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string score
//    {
//        get;
//        set;
//    }

//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string fraud
//    {
//        get;
//        set;
//    }

//    [System.Xml.Serialization.XmlTextAttribute()]
//    public string Value
//    {
//        get;
//        set;
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//public partial class Screening {
    
//    private string permissiblePurposeField;
    
//    private string specimenIdField;
    
//    private string organizationNameField;
    
//    private string titleField;
    
//    private string startDateField;
    
//    private string endDateField;
    
//    private string compensationField;
    
//    private string regionField;
    
//    private string districtField;
    
//    private string countyField;
    
//    private BackgroundCheckBackgroundSearchPackageScreeningsScreeningLinkedApplicantsOrderId[][] linkedApplicantsField;
    
//    private BackgroundCheckBackgroundSearchPackageScreeningsScreeningContactInfo[] contactInfoField;
    
//    private BackgroundCheckBackgroundSearchPackageScreeningsScreeningContact[] contactField;
    
//    private BackgroundCheckBackgroundSearchPackageScreeningsScreeningEducationHistorySchoolOrInstitution[][] educationHistoryField;
    
//    private BackgroundCheckBackgroundSearchPackageScreeningsScreeningSearchLicenseLicense[][] searchLicenseField;
    
//    private Vendor[] vendorField;
    
//    private string typeField;
    
//    private string qualifierField;
    
//    private string numberField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string PermissiblePurpose {
//        get {
//            return this.permissiblePurposeField;
//        }
//        set {
//            this.permissiblePurposeField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string SpecimenId {
//        get {
//            return this.specimenIdField;
//        }
//        set {
//            this.specimenIdField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string OrganizationName {
//        get {
//            return this.organizationNameField;
//        }
//        set {
//            this.organizationNameField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string Title {
//        get {
//            return this.titleField;
//        }
//        set {
//            this.titleField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string StartDate {
//        get {
//            return this.startDateField;
//        }
//        set {
//            this.startDateField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string EndDate {
//        get {
//            return this.endDateField;
//        }
//        set {
//            this.endDateField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string Compensation {
//        get {
//            return this.compensationField;
//        }
//        set {
//            this.compensationField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string Region {
//        get {
//            return this.regionField;
//        }
//        set {
//            this.regionField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string District {
//        get {
//            return this.districtField;
//        }
//        set {
//            this.districtField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string County {
//        get {
//            return this.countyField;
//        }
//        set {
//            this.countyField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    [System.Xml.Serialization.XmlArrayItemAttribute("OrderId", typeof(BackgroundCheckBackgroundSearchPackageScreeningsScreeningLinkedApplicantsOrderId), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public BackgroundCheckBackgroundSearchPackageScreeningsScreeningLinkedApplicantsOrderId[][] LinkedApplicants {
//        get {
//            return this.linkedApplicantsField;
//        }
//        set {
//            this.linkedApplicantsField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("ContactInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public BackgroundCheckBackgroundSearchPackageScreeningsScreeningContactInfo[] ContactInfo {
//        get {
//            return this.contactInfoField;
//        }
//        set {
//            this.contactInfoField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("Contact", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public BackgroundCheckBackgroundSearchPackageScreeningsScreeningContact[] Contact {
//        get {
//            return this.contactField;
//        }
//        set {
//            this.contactField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    [System.Xml.Serialization.XmlArrayItemAttribute("SchoolOrInstitution", typeof(BackgroundCheckBackgroundSearchPackageScreeningsScreeningEducationHistorySchoolOrInstitution), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
//    public BackgroundCheckBackgroundSearchPackageScreeningsScreeningEducationHistorySchoolOrInstitution[][] EducationHistory {
//        get {
//            return this.educationHistoryField;
//        }
//        set {
//            this.educationHistoryField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    [System.Xml.Serialization.XmlArrayItemAttribute("License", typeof(BackgroundCheckBackgroundSearchPackageScreeningsScreeningSearchLicenseLicense), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
//    public BackgroundCheckBackgroundSearchPackageScreeningsScreeningSearchLicenseLicense[][] SearchLicense {
//        get {
//            return this.searchLicenseField;
//        }
//        set {
//            this.searchLicenseField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("Vendor", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
//    public Vendor[] Vendor {
//        get {
//            return this.vendorField;
//        }
//        set {
//            this.vendorField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string type {
//        get {
//            return this.typeField;
//        }
//        set {
//            this.typeField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string qualifier {
//        get {
//            return this.qualifierField;
//        }
//        set {
//            this.qualifierField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string number {
//        get {
//            return this.numberField;
//        }
//        set {
//            this.numberField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//public partial class BackgroundCheckBackgroundSearchPackageScreeningsScreeningLinkedApplicantsOrderId {
    
//    private string valueField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlTextAttribute()]
//    public string Value {
//        get {
//            return this.valueField;
//        }
//        set {
//            this.valueField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//public partial class BackgroundCheckBackgroundSearchPackageScreeningsScreeningContactInfo {
    
//    private string telephoneField;
    
//    private PersonName[] personNameField;
    
//    private PostalAddress[] postalAddressField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string Telephone {
//        get {
//            return this.telephoneField;
//        }
//        set {
//            this.telephoneField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("PersonName")]
//    public PersonName[] PersonName {
//        get {
//            return this.personNameField;
//        }
//        set {
//            this.personNameField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("PostalAddress")]
//    public PostalAddress[] PostalAddress {
//        get {
//            return this.postalAddressField;
//        }
//        set {
//            this.postalAddressField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//public partial class BackgroundCheckBackgroundSearchPackageScreeningsScreeningContact {
    
//    private string relationshipField;
    
//    private PersonName[] personNameField;
    
//    private BackgroundCheckBackgroundSearchPackageScreeningsScreeningContactContactMethod[] contactMethodField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string Relationship {
//        get {
//            return this.relationshipField;
//        }
//        set {
//            this.relationshipField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("PersonName")]
//    public PersonName[] PersonName {
//        get {
//            return this.personNameField;
//        }
//        set {
//            this.personNameField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("ContactMethod", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public BackgroundCheckBackgroundSearchPackageScreeningsScreeningContactContactMethod[] ContactMethod {
//        get {
//            return this.contactMethodField;
//        }
//        set {
//            this.contactMethodField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//public partial class BackgroundCheckBackgroundSearchPackageScreeningsScreeningContactContactMethod {
    
//    private string telephoneField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string Telephone {
//        get {
//            return this.telephoneField;
//        }
//        set {
//            this.telephoneField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//public partial class BackgroundCheckBackgroundSearchPackageScreeningsScreeningEducationHistorySchoolOrInstitution {
    
//    private string schoolNameField;
    
//    private BackgroundCheckBackgroundSearchPackageScreeningsScreeningEducationHistorySchoolOrInstitutionLocationSummary[] locationSummaryField;
    
//    private BackgroundCheckBackgroundSearchPackageScreeningsScreeningEducationHistorySchoolOrInstitutionDegree[] degreeField;
    
//    private BackgroundCheckBackgroundSearchPackageScreeningsScreeningEducationHistorySchoolOrInstitutionDatesOfAttendanceStartDate[][] datesOfAttendanceField;
    
//    private string schoolTypeField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string SchoolName {
//        get {
//            return this.schoolNameField;
//        }
//        set {
//            this.schoolNameField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("LocationSummary", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public BackgroundCheckBackgroundSearchPackageScreeningsScreeningEducationHistorySchoolOrInstitutionLocationSummary[] LocationSummary {
//        get {
//            return this.locationSummaryField;
//        }
//        set {
//            this.locationSummaryField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("Degree", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public BackgroundCheckBackgroundSearchPackageScreeningsScreeningEducationHistorySchoolOrInstitutionDegree[] Degree {
//        get {
//            return this.degreeField;
//        }
//        set {
//            this.degreeField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    [System.Xml.Serialization.XmlArrayItemAttribute("StartDate", typeof(BackgroundCheckBackgroundSearchPackageScreeningsScreeningEducationHistorySchoolOrInstitutionDatesOfAttendanceStartDate), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
//    public BackgroundCheckBackgroundSearchPackageScreeningsScreeningEducationHistorySchoolOrInstitutionDatesOfAttendanceStartDate[][] DatesOfAttendance {
//        get {
//            return this.datesOfAttendanceField;
//        }
//        set {
//            this.datesOfAttendanceField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string schoolType {
//        get {
//            return this.schoolTypeField;
//        }
//        set {
//            this.schoolTypeField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//public partial class BackgroundCheckBackgroundSearchPackageScreeningsScreeningEducationHistorySchoolOrInstitutionLocationSummary {
    
//    private string municipalityField;
    
//    private string regionField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string Municipality {
//        get {
//            return this.municipalityField;
//        }
//        set {
//            this.municipalityField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string Region {
//        get {
//            return this.regionField;
//        }
//        set {
//            this.regionField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//public partial class BackgroundCheckBackgroundSearchPackageScreeningsScreeningEducationHistorySchoolOrInstitutionDegree {
    
//    private string degreeNameField;
    
//    private string degreeTypeField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string DegreeName {
//        get {
//            return this.degreeNameField;
//        }
//        set {
//            this.degreeNameField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string degreeType {
//        get {
//            return this.degreeTypeField;
//        }
//        set {
//            this.degreeTypeField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//public partial class BackgroundCheckBackgroundSearchPackageScreeningsScreeningEducationHistorySchoolOrInstitutionDatesOfAttendanceStartDate {
    
//    private string stringDateField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string StringDate {
//        get {
//            return this.stringDateField;
//        }
//        set {
//            this.stringDateField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//public partial class BackgroundCheckBackgroundSearchPackageScreeningsScreeningSearchLicenseLicense {
    
//    private string licenseNumberField;
    
//    private string licensingAgencyField;
    
//    private string licenseNameField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string LicenseNumber {
//        get {
//            return this.licenseNumberField;
//        }
//        set {
//            this.licenseNumberField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string LicensingAgency {
//        get {
//            return this.licensingAgencyField;
//        }
//        set {
//            this.licensingAgencyField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string LicenseName {
//        get {
//            return this.licenseNameField;
//        }
//        set {
//            this.licenseNameField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//public partial class Vendor {
    
//    private string scoreField;
    
//    private string fraudField;
    
//    private string typeField;
    
//    private string hawkalertField;
    
//    private string valueField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string score {
//        get {
//            return this.scoreField;
//        }
//        set {
//            this.scoreField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string fraud {
//        get {
//            return this.fraudField;
//        }
//        set {
//            this.fraudField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string type {
//        get {
//            return this.typeField;
//        }
//        set {
//            this.typeField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string hawkalert {
//        get {
//            return this.hawkalertField;
//        }
//        set {
//            this.hawkalertField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlTextAttribute()]
//    public string Value {
//        get {
//            return this.valueField;
//        }
//        set {
//            this.valueField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//public partial class BackgroundCheckBackgroundSearchPackageScreeningsAdditionalItems {
    
//    private string textField;
    
//    private string typeField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string Text {
//        get {
//            return this.textField;
//        }
//        set {
//            this.textField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string type {
//        get {
//            return this.typeField;
//        }
//        set {
//            this.typeField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
//public partial class NewDataSet {
    
//    private object[] itemsField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("BackgroundCheck", typeof(BackgroundCheck))]
//    [System.Xml.Serialization.XmlElementAttribute("PersonName", typeof(PersonName))]
//    [System.Xml.Serialization.XmlElementAttribute("PostalAddress", typeof(PostalAddress))]
//    public object[] Items {
//        get {
//            return this.itemsField;
//        }
//        set {
//            this.itemsField = value;
//        }
//    }
//}
